---
name: Build Application Binaries

on: workflow_dispatch

jobs:
  build-binaries:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'true'
      - uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.x
      - run: dotnet build
