---
name: Build Application Binaries

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-binaries:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'true'
      - uses: actions/setup-dotnet@v1
      - run: dotnet build
