---
name: Build Application Binaries

on: [workflow_dispatch, push]

jobs:
  publish_binaries:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
            submodules: 'true'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.x
      - name: Build and publish binaries
        run: dotnet publish -o dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: app-binaries
            path: dist
        